version: '3'
services:

  eventstore:
    image: eventstore/eventstore:release-4.1.0
    ports:
      - "2113:2113"
      - "1113:1113"
    logging:
      driver: "none"

  nats:
    image: nats:1.1.0-linux
    expose:
      - "4222"
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    depends_on:
      - eventstore
    logging:
      driver: "none"
